### ISSUE TITLE
How to predict the result of your stacking process

### ISSUE THREAD

**Issue by armgilles** [rushter/heamy#3]
Hi,

First thanks for your work, I'm pretty existing to test it and play with it !

I search on documentation and examples but can't find it. I would like to use my stacking process and predict the result (like .predict() in Scikit)

I made a [notebook](https://gist.github.com/armgilles/e2ce207283813d0f91f60d870df416be) to illustrate my problem.

I'm pretty sure I miss something...

A.

**Comment by rushter** [comment]
Hi, 

Unfortunately there is no such a function. 
This package designed for quick experiments. 

You can join `X_validation` with `X_train` and then specify train/test indices for `validate` method.
Or you can simply replace `X_test` with `X_validation`.
```
d = Dataset(X_train+X_validate, y_train, X_test)
# Positional indices
train_ind = np.array(range(0, 70))
X_validate_ind = np.array(range(70, 100))
...
# Validate using X_validate_ind 
stacker.validate(k=1,scorer=mean_absolute_error,indices=(train_ind,X_validate_ind))

# Get results for X_test 
results = stacker.predict()
mean_absolute_error(y_test, results)
```


I will definitely fix this problem in a future.

Heamy doesn't know how to save internal state for every ml package. So it's not an easy task if you go beyond skickit-learn.

**Comment by armgilles** [comment]
Thanks for your answer.

So I can't use it (currently) to submit my prediction to a Kaggle contest (*sad*) .

I'ill follow the dev of ```Heamy```

**Comment by rushter** [comment]
@armgilles You can definitely do this :). 
I use it only for kaggle. 

Snippet from bimbo competition:

```
def first_dataset():
    drop_list = ['Town', 'Demanda_uni_equil', 'Ruta_SAK', 'Dev_proxima', 'short_name_processed', 'brand', 'Canal_ID',
                 'Venta_uni_hoy', 'Venta_hoy', 'State', 'Producto_ID', 'Agencia_ID', 'NombreProducto',
                 'Dev_uni_proxima',
                 'Semana', 'Cliente_ID', 'id']

    train = pd.read_hdf('data/train.csv')
    test = pd.read_hdf('data/test.csv')
    y_train = train['Demanda_uni_equil']
    ...
    
    return {'X_train': train, 'X_test': test, 'y_train': y_train}


def xgb_model(X_train, y_train, X_test, y_test=None, random_state=9999):
    params = {
        'objective': 'reg:linear',
        'learning_rate': 0.02,
        'max_depth': 20,
        'subsample': 0.8,
        'colsample_bytree': 0.8,
        'seed': random_state,
        'num_estimators': 100,
        'silent': 1,
        'tree_method': 'exact',

    }
    na_value = np.nan

    X_train = xgb.DMatrix(X_train, label=y_train, missing=na_value)
    model = xgb.train(params, X_train, params['num_estimators'], maximize=True, )
    return model.predict(xgb.DMatrix(X_test, missing=na_value))
    
def submit(predictions, name):
    print predictions.shape
    df = pd.read_csv('data/sample_submission.csv')
    df['Demanda_uni_equil'] = predictions
    df = df[['Demanda_uni_equil', 'id']]
    if not os.path.exists('submissions'):
        os.mkdir('submissions')
    df.to_csv('submissions/%s.csv' % name, index=False)

ds = Dataset(preprocessor=first_dataset, use_cache=False)
pipe = ModelsPipeline(
    Regressor(dataset=ds, estimator=xgb_model, use_cache=True),
    Regressor(dataset=ds, estimator=xgb_model2, use_cache=True),
    ..
)
stack_ds = pipe.stack(k=4, seed=333, add_diff=True)
stack_model = Regressor(dataset=stack_ds, estimator=xgb_stack, use_cache=True, parameters={'random_state': 1123567})
# Get predictions for test
predictions = stack_model.predict()
# Save to csv
submit(predictions, name='res-%s' % (time.time()))
```

**Comment by armgilles** [comment]
Wow congratulation for your top 10 ! 

The dataset was pretty huge, your CPU burned a lot I guess :)

Yeah I think you did a pretty heavy features selection + tunning + ensemble to reach this score.

A.

**Comment by unnir** [comment]
@rushter  
hi, could you please upload the file with description of your approach once again? The link is broken now...

**Comment by rushter** [comment]
@unnir There was no description, just a screenshot of my project structure.
