### ISSUE TITLE
[question] feature encoding - save state

### ISSUE THREAD

**Issue by geoHeil** [rushter/heamy#4]
Hi,

does this really work to one hot encode features to always the same labels? I think of deploying my model as an api where possibly new labels will show up. 

- your implementation only seems to handle the existing labels e.g. no possibility to error / ignore fresh incoming labels
- for me it is unclear how the labels are stored in a pipeline so that new incoming data can be encoded with fitting labels.

```
train[column] = train[column].astype('category', categories=categories)
test[column] = test[column].astype('category', categories=categories)
# from: https://github.com/rushter/heamy/blob/master/heamy/feature.py
```

**Comment by rushter** [comment]
Hi, 

Unfortunately my library designed only for experiments with fixed dataset.  
It's not production ready.
